name: "Terraform"
on:
  push:
    branches: ["main"]
    paths: ["src/**"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
     - name: "Configurando AWS credentials"
       uses: aws-actions/configure-aws-credentials@v4
       with:
          aws-region: us-east-1
          aws-access-key-id: ${{secrets.AWS_ACESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACESS_KEY_ID}}
     - name: "Checkout"
       uses: actions/checkout@v4

     - name: "Terraform init"
       run: "terraform init"

     - name: "Terraform Apply"
       run: "terraform apply --auto-aprove"